maykinmedia/objecttypes-api

src/objecttypes/api/filters.py
src/objecttypes/api/views.py
src/objecttypes/conf/api.py
src/objecttypes/tests/test_filters.py
src/openapi.yaml
src/swagger2.0.json

Sorry @annashamray, no test added.

Added public filter on Objecttypes

---

.travis.yml
bin/docker_push.sh

fixes https://github.com/maykinmedia/objects-api/issues/43

Push docker image cia Travis

---

.bumpversion.cfg
appstore.yaml
publiccode.yaml

Fixes https://github.com/maykinmedia/objects-api/issues/94

Added publiccode

---

README.NL.rst
README.rst

Fixes https://github.com/maykinmedia/objects-api/issues/127

Corrected docs link.

---

src/objecttypes/core/admin.py

fixes https://github.com/maykinmedia/objects-api/issues/117

colorize json_schema in the admin

---

src/objecttypes/api/serializers.py
src/objecttypes/api/validators.py
src/objecttypes/core/admin.py
src/objecttypes/tests/test_objecttype_api.py
src/objecttypes/tests/test_validation.py
src/openapi.yaml

Issue - https://github.com/maykinmedia/objects-api/issues/156

Feature/admin add UUID

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml
src/objecttypes/conf/api.py
src/openapi.yaml

fixes https://github.com/maykinmedia/objects-api/issues/187

:bookmark: release 1.1.0

---

.github/workflows/quick_start.yml

Issue - https://github.com/maykinmedia/objects-api/issues/203

add createsuperuser to ci check

---

src/objecttypes/core/admin.py
src/objecttypes/core/forms.py
src/objecttypes/core/widgets.py
src/objecttypes/tests/test_objecttype_admin.py
src/objecttypes/tests/test_widgets.py

fixes: https://github.com/maykinmedia/objects-api/issues/253

:bug: Fix JSONSuit widget for invalid JSON values

---

src/objecttypes/conf/base.py

Same PR as https://github.com/maykinmedia/objects-api/pull/289, fixes APM configuration

:bug: Fix Elastic APM configuration

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

:arrow_up: bump django to 3.2.19

---

src/objecttypes/conf/base.py

Add email environment variables, same as https://github.com/maykinmedia/objects-api/pull/366

Add email environment variables

---

src/objecttypes/scss/admin/_app_overrides.scss

fixes: maykinmedia/objects-api#392

:lipstick:[maykinmedia/objecttypes-api#392] fix styling of OIDC login

---

.github/workflows/codeql-analysis.yml

fixes https://github.com/maykinmedia/objects-api/issues/391 (codeQL part)
I've made the same codfig as in Objects API, let's hope it will help

fix CodeQL

---

CHANGELOG.rst

Forgot to update it in the settings refactor PR https://github.com/maykinmedia/objecttypes-api/pull/102/files

:memo: Update changelog

---

src/objecttypes/api/mixins.py
src/objecttypes/api/v1/views.py
src/objecttypes/api/v2/views.py
src/objecttypes/tests/v1/test_objectversion_api.py
src/objecttypes/tests/v2/test_objectversion_api.py

fixes https://github.com/maykinmedia/objects-api/issues/361

list versions with incorrect objecttype uuid

---

.github/workflows/ci.yml
.github/workflows/code-quality.yml
Dockerfile
INSTALL.rst
src/objecttypes/accounts/models.py
src/objecttypes/api/urls.py
src/objecttypes/api/v1/urls.py
src/objecttypes/api/v2/urls.py

fixes https://github.com/maykinmedia/objects-api/issues/379 (Objecttypes part)

use python3.11

---

src/objecttypes/scss/admin/_admin_theme.scss

fixes https://github.com/open-zaak/open-notificaties/issues/150 (Objecttypes part)

:lipstick: fix help-text icon style in the admin

---

.github/workflows/ci.yml
.github/workflows/code-quality.yml
bin/generate_schema.sh
src/objecttypes/api/v1/openapi.yaml
src/objecttypes/api/v2/openapi.yaml

Partially fixes https://github.com/maykinmedia/open-api-framework/issues/17

[#17] add CI jobs to detect uncommitted OAS changes

---

requirements/ci.txt
requirements/dev.txt

:arrow_up: [#50] fixed last dependacy issue

---

Dockerfile
package-lock.json

fixes #50 
Updated setuptools in dockerfile
fixed npm vulnerabilities

:art: [#50] updated setuptools in docker and fixed npm vulnerabilities

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml
src/objecttypes/api/v2/openapi.yaml
src/objecttypes/conf/api.py

fixes https://github.com/maykinmedia/objects-api/issues/436 (Objecttypes part)

:bookmark: release 2.2.1

---

.github/workflows/ci.yml

see https://github.com/maykinmedia/objects-api/issues/463

Disable trivy image scan job

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

fixes https://github.com/maykinmedia/open-api-framework/issues/66
depends on https://github.com/maykinmedia/commonground-api-common/pull/45

bump zgw-consumers to 0.35.1, commonground-api-common to 2.0.1, OAF to 0.9.0

---

.github/workflows/quick_start.yml
.github/workflows/trivy-db-cache.yml

Fixes maykinmedia/objects-api#463 partially
Also fixes quickstart failing due to migrations not being done yet

:construction_worker: [maykinmedia/objects-api#463] Add cache job for trivy

---

src/objecttypes/urls.py

fixes: https://github.com/maykinmedia/open-api-framework/issues/79
**Changes**
Disables the admin nav sidebar

[maykinmedia/open-api-framework#79] disable admin nav sidebar

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml

Fixes https://github.com/maykinmedia/objects-api/issues/531

:bookmark: release 3.0.1

---

.github/workflows/ci.yml

and replaced it with a basic script

:construction_worker: Remove changed-files actions from CI

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes https://github.com/maykinmedia/objects-api/issues/575

:bookmark: Release 3.0.3

---

.github/workflows/code-quality.yml
.pre-commit-config.yaml
CONTRIBUTING.md
INSTALL.rst
README.NL.rst
README.rst
requirements/ci.txt
requirements/dev.in
requirements/dev.txt
requirements/test-tools.in
ruff.toml
setup.cfg
src/objecttypes/accounts/management/commands/createinitialsuperuser.py
src/objecttypes/accounts/tests/test_createinitialsuperuser.py
src/objecttypes/conf/dev.py
src/objecttypes/core/widgets.py

Fixes #[maykinmedia/open-api-framework#133]
Workflow: https://github.com/maykinmedia/open-api-workflows/pull/23

:art: [maykinmedia/open-api-framework#133] Refactor code with ruff

---

.github/workflows/ci.yml
.github/workflows/code-quality.yml
.github/workflows/oaf-check.yml
.github/workflows/oas.yml
Dockerfile
INSTALL.rst
README.NL.rst
README.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
ruff.toml

Partially fixes #https://github.com/maykinmedia/open-api-framework/issues/140
Partially fixes #https://github.com/maykinmedia/open-api-framework/issues/132

:arrow_up: [maykinmedia/open-api-framework#140] Upgrade python to 3.12

---

.bumpversion.cfg
CHANGELOG.rst
Dockerfile
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes https://github.com/maykinmedia/objects-api/issues/608

:bookmark: Release 3.0.4

---

.github/workflows/ci.yml
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/objecttypes/accounts/tests/test_oidc.py
src/objecttypes/conf/base.py

Fixes #[objecttypes/6](https://github.com/maykinmedia/objects-api/issues/607)
**Changes**
added connection pooling

:sparkles: [#607] introduce connection pooling

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes maykinmedia/open-api-framework#172
**Changes**
[Describe the changes here]

⬆️  [maykinmedia/open-api-framework#172] Upgrade zgw-consumers to 1.0.0

---

src/objecttypes/conf/base.py
src/objecttypes/setup.py

Fixes maykinmedia/open-api-framework#179
**Changes**
[Describe the changes here]

 :sparkles: [maykinmedia/open-api-framework#179] Monkeypatch request to set default timeout

---

CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml
pyproject.toml

Fixes #https://github.com/maykinmedia/objects-api/issues/656

:bookmark: Release 3.2.1

---

CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml
pyproject.toml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes maykinmedia/objects-api#680

🔖 Release 3.3.0
